Import debian 2.7.4-2 packaging
This merges the debian packaging from sid's 2.7.4-2 version. Most
everything from there has been preferred. The only remaining change is
to keep the xz-utils dependency for obs-worker, which I believe should
be in debian's package.

https://phabricator.endlessm.com/T14726

diff --git a/debian/obs-worker.obsworker.init b/debian/obs-worker.obsworker.init
--- a/debian/obs-worker.obsworker.init
+++ b/debian/obs-worker.obsworker.init
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 # Copyright (c) 2007-2011, SUSE Inc.
 #
 # Author: adrian@suse.de
@@ -7,8 +7,8 @@
 #
 ### BEGIN INIT INFO
 # Provides:          obsworker
-# Required-Start:    $time $network $syslog $local_fs
-# Required-Stop:     $time $network $syslog $local_fs
+# Required-Start:    $time $network $syslog $local_fs $remote_fs
+# Required-Stop:     $time $network $syslog $local_fs $remote_fs
 # Should-Start:      $remote_fs obsstoragesetup obssrcserver obsrepserver xendomains
 # Should-Stop:       $none
 # Default-Start:     2 3 4 5
@@ -16,14 +16,20 @@
 # Description:       Open Build Service worker
 ### END INIT INFO
 
-set -e 
+set -e
 
 NAME="obsworker"
 DESC="openSUSE Buildservice worker"
 DEFAULTS="/etc/default/obsworker"
 
+. /lib/lsb/init-functions
+
 if [ -f "${DEFAULTS}" ];then
     . "${DEFAULTS}"
+fi
+
+if [ -z "$OBS_SRC_SERVER" ]; then
+	OBS_SRC_SERVER="localhost:5352"
 fi
 
 # Preconfigured by obsstoragesetup runlevel setup script
@@ -31,9 +37,6 @@ if [ -f /etc/buildhost.config ];then
     . /etc/buildhost.config
 fi
 
-if [ -z "$OBS_SRC_SERVER" ]; then
-        OBS_SRC_SERVER="localhost:5352"
-fi
 if [ -z "$OBS_WORKER_DIRECTORY" ]; then
     OBS_WORKER_DIRECTORY="/var/cache/obs/worker"
 fi
@@ -54,6 +57,9 @@ if [ -n "$OBS_WORKER_TEST_MODE" ]; then
 fi
 if [ -n "$OBS_WORKER_JOBS" ]; then
     OBS_JOBS="--jobs $OBS_WORKER_JOBS"
+fi
+if [ -n "$OBS_WORKER_THREADS" ]; then
+    OBS_THREADS="--threads $OBS_WORKER_THREADS"
 fi
 if [ -n "$OBS_WORKER_NICE_LEVEL" ]; then
     OBS_NICE=$OBS_WORKER_NICE_LEVEL
@@ -80,41 +86,128 @@ if [ -n "$OBS_CACHE_SIZE" -a -n "$OBS_CACHE_DIR" ]; then
 fi
 
 if [ -n "$OBS_VM_KERNEL" -a "$OBS_VM_KERNEL" != "none" ] ; then
-    if [ -n "$OBS_VM_INITRD" -a "$OBS_VM_INITRD" != "none" ] ; then
-        OBS_WORKER_OPT="$OBS_WORKER_OPT --vm-kernel $OBS_VM_KERNEL  --vm-initrd $OBS_VM_INITRD"
-    fi
+    OBS_WORKER_OPT="$OBS_WORKER_OPT --vm-kernel $OBS_VM_KERNEL"
+fi
+
+if [ -n "$OBS_VM_INITRD" -a "$OBS_VM_INITRD" != "none" ] ; then
+    OBS_WORKER_OPT="$OBS_WORKER_OPT --vm-initrd $OBS_VM_INITRD"
 fi
 
 if [ -n "$OBS_WORKER_LOCALKIWI_DIRECTORY" ]; then
     OBS_WORKER_OPT="$OBS_WORKER_OPT --localkiwi $OBS_WORKER_LOCALKIWI_DIRECTORY --arch local"
 fi
 
-[ -z "$OBS_INSTANCE_MEMORY" ] && OBS_INSTANCE_MEMORY=256
+if [ -n "$OBS_WORKER_BINARIES_PROXY" ]; then
+    OBS_WORKER_OPT="$OBS_WORKER_OPT --getbinariesproxy $OBS_WORKER_BINARIES_PROXY"
+fi
+
+if [ -n "$OBS_VM_ENABLE_CONSOLE" ]; then
+    OBS_WORKER_OPT="$OBS_WORKER_OPT --vm-enable-console"
+fi
+
+[ -z "$OBS_INSTANCE_MEMORY" ] && OBS_INSTANCE_MEMORY=512
 
 vmopt=
 
+ARCH=""
+EMULATOR=""
 if [ -n "$OBS_VM_TYPE" -a "$OBS_VM_TYPE" != "auto" ] ; then
-    if [ "$OBS_VM_TYPE" != "none" ] ; then
+    if [ "${OBS_VM_TYPE#emulator:}" != "$OBS_VM_TYPE" ] ; then
+        vmopt="--emulator"
+        options=(${OBS_VM_TYPE//:/ })
+        ARCH="--arch ${options[1]}"
+        [ -n "${options[2]}" ] && EMULATOR="--emulator-script ${options[2]}"
+    elif [ "$OBS_VM_TYPE" != "none" ] ; then
         vmopt="--$OBS_VM_TYPE"
     fi
-elif [ -e /dev/kvm ] ; then
+elif [ -e /dev/kvm -a -x /usr/bin/qemu-kvm ] ; then
     vmopt=--kvm
-elif [ -e /sys/hypervisor/type ] && grep -q xen /sys/hypervisor/type; then
+    OBS_VM_TYPE="kvm"
+elif [ -e /sys/hypervisor/type ] && [ -x /usr/sbin/xl -o -x /usr/sbin/xm ] && grep -q xen /sys/hypervisor/type; then
     vmopt=--xen
+    OBS_VM_TYPE="xen"
 fi
 
-if [ -n "$vmopt" -a "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" ]; then
+if [ "$OBS_VM_TYPE" = "zvm" ]; then
+    # for z/VM, the disks are already setup with the workers.
+    if [ -n "$OBS_VM_DISK_AUTOSETUP_FILESYSTEM" ]; then
+            VMDISK_FILESYSTEM="--vmdisk-filesystem ${OBS_VM_DISK_AUTOSETUP_FILESYSTEM}"
+    fi
+    if [ -n "$OBS_VM_DISK_AUTOSETUP_MOUNT_OPTIONS" ]; then
+            VMDISK_MOUNT_OPTIONS="--vmdisk-mount-options ${OBS_VM_DISK_AUTOSETUP_MOUNT_OPTIONS}"
+    fi
+    if [ -n "$OBS_VM_DISK_CLEAN" ];then
+            VMDISK_CLEAN="--vmdisk-clean"
+    fi
+fi
+
+if [ "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" -o "${OBS_VM_TYPE#emulator:}" != "$OBS_VM_TYPE" ] ; then
     # we start up in VM mode, check for the worker disk options
-    if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" -a -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
+    if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" ]; then
         VMDISK_ROOT_FILESIZE="--vmdisk-rootsize ${OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE}"
-        VMDISK_SWAP_FILESIZE="--vmdisk-swapsize ${OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE}"
+        if [ -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
+            VMDISK_SWAP_FILESIZE="--vmdisk-swapsize ${OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE}"
+        fi
         if [ -n "$OBS_VM_DISK_AUTOSETUP_FILESYSTEM" ]; then
             VMDISK_FILESYSTEM="--vmdisk-filesystem ${OBS_VM_DISK_AUTOSETUP_FILESYSTEM}"
+        fi
+        if [ -n "$OBS_VM_DISK_AUTOSETUP_MOUNT_OPTIONS" ]; then
+            VMDISK_MOUNT_OPTIONS="--vmdisk-mount-options ${OBS_VM_DISK_AUTOSETUP_MOUNT_OPTIONS}"
+        fi
+        if [ -n "$OBS_VM_DISK_CLEAN" ];then
+            VMDISK_CLEAN="--vmdisk-clean"
         fi
     fi
 fi
 
-#rc_reset
+check_vmcp()
+{
+	# try to load the kernel module
+	modprobe vmcp 2> /dev/null || :
+	# run a vmcp command that always works from within z/VM
+	vmcp q privclass
+}
+
+create_initrd()
+{
+        # $1 name of kernel
+        # $2 name of initrd
+        # 0150 is already included from the local guest
+        if test -z "$2" ; then
+                echo "Please define a name for the new initrd in /etc/sysconfig/obs-server"
+                return 1
+        else
+		# create initrd with system scripts
+                mkinitrd -k $1 -i $2 -m "xfs reiserfs ext3 ext4 fat vfat" -B -S
+                TEMPDIR=$(mktemp -d /tmp/initrd.XXX)
+                pushd $TEMPDIR
+		# unpack initrd to add some extra files 
+                zcat $2 | cpio -i
+                cat - > etc/udev/rules.d/51-dasd-0.0.0250.rules <<EOF
+ACTION=="add", SUBSYSTEM=="ccw", KERNEL=="0.0.0250",
+IMPORT{program}="collect 0.0.0250 %k 0.0.0250 dasd-eckd"
+ACTION=="add", SUBSYSTEM=="drivers", KERNEL=="dasd-eckd",
+IMPORT{program}="collect 0.0.0250 %k 0.0.0250 dasd-eckd"
+ACTION=="add", ENV{COLLECT_0.0.0250}=="0", ATTR{[ccw/0.0.0250]online}="1"
+EOF
+                # lets activate the alias devices too
+                for device in {1..2}E{C..F}; do
+                cat - > etc/udev/rules.d/51-dasd-0.0.0${device}.rules <<EOF
+ACTION=="add", SUBSYSTEM=="ccw", KERNEL=="0.0.0${device}",
+IMPORT{program}="collect 0.0.0${device} %k 0.0.0${device} dasd-eckd"
+ACTION=="add", SUBSYSTEM=="drivers", KERNEL=="dasd-eckd",
+IMPORT{program}="collect 0.0.0${device} %k 0.0.0${device} dasd-eckd"
+ACTION=="add", ENV{COLLECT_0.0.0${device}}=="0", ATTR{[ccw/0.0.0${device}]online}="1"
+EOF
+                done
+                cp -a /usr/sbin/xfs_check /sbin/fsck.xfs /usr/sbin/xfs_db sbin/
+		# create new initrd:
+                find . | cpio -H newc -o | gzip -9 -c > $2
+                popd
+                rm -rf $TEMPDIR
+        fi
+}
+
 case "$1" in
     start)
         # reset screenrc
@@ -122,9 +215,8 @@ case "$1" in
         chown obsworker:obsworker "$obsrundir"
         rm -rf "$workerdir"
         mkdir -p "$workerbootdir"
-#        echo "zombie on"       > $screenrc
-        echo "caption always" >> $screenrc
-        chown -R obsworker:obsworker "$workerdir"
+        echo "zombie on"       > $screenrc
+        echo 'caption always "%3n %t%? [%h]%?"' >> $screenrc
 
         if [ 0"$OBS_WORKER_INSTANCES" -gt 0 ]; then
             NUM="$OBS_WORKER_INSTANCES"
@@ -132,12 +224,26 @@ case "$1" in
             # start one build backend per CPU
             NUM=`ls -d /sys/devices/system/cpu/cpu[0-9]* | wc -l`
         fi
+	if [ "--zvm" == "$vmopt" ]; then
+	    check_vmcp
+	    create_initrd $OBS_VM_KERNEL $OBS_VM_INITRD
+            if [ -n "$OBS_WORKER_INSTANCE_NAMES" ]; then
+                WORKERS=($OBS_WORKER_INSTANCE_NAMES)
+                NUM=${#WORKERS[*]}
+            fi
+	fi
+
+        if [ -n "$OBS_WORKER_OWNER" ]; then
+            HOSTOWNER="--owner $OBS_WORKER_OWNER"
+        fi
 
 	# print some config data
         echo "Run $NUM obsworker using $OBS_WORKER_DIRECTORY"
         echo -n "Type of obsworker is "
 	if [ "--kvm" == "$vmopt" ]; then echo "KVM virtual machine"
 	elif [ "--xen" == "$vmopt" ]; then echo "XEN virtual machine"
+	elif [ "--zvm" == "$vmopt" ]; then echo "z/VM virtual machine"
+	elif [ "--emulator" == "$vmopt" ]; then echo "System emulated virtual machine"
 	else  echo "chroot"
 	fi
 
@@ -156,16 +262,24 @@ case "$1" in
         echo "Fetching initial worker code from $WORKER_CODE"
         mkdir -p "$workerbootdir"
         pushd "$workerbootdir" > /dev/null
-        if ! $(curl -s "$WORKER_CODE"/getworkercode | cpio --quiet --extract)
-        then
-            echo "E: Failure when fetching worker code from server."
-        else
-            echo "Fetched worker code from server."
-        fi
+        I=0
+        while ! curl -s "$WORKER_CODE"/getworkercode | cpio --quiet --extract ; do
+          # we need to wait for rep server maybe
+          echo >&2 "WARNING: Could not reach rep server $WORKER_CODE. Trying again."
+          I=$(( $I + 1 ))
+          if test "10" -lt "$I"; then
+             echo >&2 "ERROR: Unable to reach rep server $WORKER_CODE!"
+             exit 1
+          fi
+          sleep 10
+        done
         ln -s . XML 
         chmod 755 bs_worker
         popd > /dev/null
 
+        for i in $OBS_WORKER_HOSTLABELS; do
+           HOSTLABELS="$HOSTLABELS --hostlabel $i"
+        done
         OBS_WORKER_OPT1="$OBS_WORKER_OPT"
         I=0
         while test "$NUM" -gt "$I"; do
@@ -174,20 +288,25 @@ case "$1" in
             else
                 port=""
             fi
+	    I_INDEX=$I
             I=$(( $I + 1 ))
-            title="$HOSTNAME/$I"
+	    if [ "$OBS_VM_TYPE" = 'zvm' ]; then
+		WORKERID="${HOSTNAME}:${WORKERS[$I_INDEX]}"
+	    else
+                WORKERID="${HOSTNAME}:$I"
+	    fi
             R=$OBS_WORKER_DIRECTORY/root_$I
             # prepare obsworker startup in screen...
             TMPFS=
-            if [ -n "$vmopt" -a "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" ]; then
+            if [ "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" -o "${OBS_VM_TYPE#emulator:}" != "$OBS_VM_TYPE" ] ; then
                 mkdir -p $R
                 DEVICE="$OBS_WORKER_DIRECTORY/root_$I/root"
                 SWAP="$OBS_WORKER_DIRECTORY/root_$I/swap"
-                if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" -a -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
-                    OBS_WORKER_OPT="$OBS_WORKER_OPT1 $VMDISK_AUTOSETUP $VMDISK_ROOT_FILESIZE $VMDISK_SWAP_FILESIZE $VMDISK_FILESYSTEM"
-                elif [ ! -e "$DEVICE" -o ! -e "$SWAP" ]; then
-                        echo "ERROR: worker is configured to use a VM, but one or all of the following devices/files do not exist: $DEVICE, $SWAP"
-                        exit 1
+                if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" ]; then
+                    OBS_WORKER_OPT="$OBS_WORKER_OPT1 $VMDISK_AUTOSETUP $VMDISK_ROOT_FILESIZE $VMDISK_SWAP_FILESIZE $VMDISK_FILESYSTEM $VMDISK_MOUNT_OPTIONS $VMDISK_CLEAN"
+                elif [ ! -e "$DEVICE" ]; then
+                    echo "ERROR: worker is configured to use a VM, but the root device do not exist: $DEVICE"
+                    exit 1
                 fi
                 if [ -n "$OBS_VM_USE_TMPFS" ]; then
                     TMPFS="--tmpfs"
@@ -195,15 +314,25 @@ case "$1" in
                 DEVICE="--device $DEVICE"
                 SWAP="--swap $SWAP"
                 MEMORY="--vm-memory $OBS_INSTANCE_MEMORY"
+                if [ -n "$OBS_VM_USE_HUGETLBFS" ]; then
+                    HUGETLBFS="--hugetlbfs $OBS_VM_USE_HUGETLBFS"
+                fi
+	    elif [ -n "$vmopt" -a "$OBS_VM_TYPE" = 'zvm' ]; then
+		mkdir -p $R
+		# Without a worker being defined, we would not be in this loop.
+		WORKER="--vm-worker ${WORKERS[$I_INDEX]}"
+		WORKER_NR="--vm-worker-nr $I"
+		OBS_WORKER_OPT="$OBS_WORKER_OPT1 $WORKER $WORKER_NR $VMDISK_FILESYSTEM $VMDISK_MOUNT_OPTIONS $VMDISK_CLEAN"
             else
                 mkdir -p $R
                 DEVICE=
                 SWAP=
                 MEMORY=
             fi
-	    echo "screen -t $title nice -n $OBS_NICE ./bs_worker $vmopt $port --root $R" \
-                "--statedir $workerdir/$I --id $HOSTNAME/$I $REPO_PARAM" \
-                "$OBS_JOBS $OBS_TEST $OBS_WORKER_OPT $TMPFS $DEVICE $SWAP $MEMORY" \
+	    echo "screen -t $WORKERID nice -n $OBS_NICE ./bs_worker --hardstatus $vmopt $port --root $R" \
+                "--statedir $workerdir/$I --id $WORKERID $REPO_PARAM $HUGETLBFS $HOSTLABELS" \
+                "$HOSTOWNER $OBS_JOBS $OBS_THREADS $OBS_TEST $OBS_WORKER_OPT $TMPFS $DEVICE $SWAP $MEMORY" \
+                "$ARCH $EMULATOR" \
                 >> $screenrc
 	    mkdir -p $workerdir/$I
         done
@@ -224,36 +353,25 @@ case "$1" in
         killall bs_worker 2>/dev/null
         sleep 2
         killall -s 9 bs_worker 2>/dev/null
-        #rc_status -v
     ;;
     restart)
         ## If first returns OK call the second, if first or
         ## second command fails, set echo return value.
         $0 stop
         $0 start
-        #rc_status
     ;;
-    try-restart)
+    try-restart|reload)
         $0 status
         if test $? = 0; then
             $0 restart
-        #else
-        #    rc_reset        # Not running is not a failure.
         fi
         # Remember status and be quiet
-        #rc_status
     ;;
-    force-reload|reload)
-    ;;
-    status)
-        echo -n "Checking for obsworker: "
-		echo "W: not implemented"
-        #checkproc bs_worker
-        #rc_status -v
+    status|force-reload)
+	echo "W: not implemented."
     ;;
     *)
-        echo "Usage: $0 {start|stop|status|try-restart|restart|reload}"
+        echo "Usage: $0 {start|stop|status|try-restart|restart|reload|force-reload}"
         exit 1
     ;;
 esac
-#rc_exit
